/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.ejercicioDBO4;
import exc.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author Mikel
 */
public class VentanaAltaPerson extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAltaPerson
     */
    public VentanaAltaPerson() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public VentanaAltaPerson(ArrayList<String> ListaCB, ArrayList<String> ListNifEmp){
        initComponents();
        setLocationRelativeTo(null);
        for(int x = 0; ListaCB.size()>x; x++){
        String Nombre = ListaCB.get(x);
        jCBEvento.addItem(Nombre);
        }
        
        for(int x = 0; ListNifEmp.size()>x; x++){
        String NifEmp = ListNifEmp.get(x);
        jCBNifEmp.addItem(NifEmp);
        }
        jCBNifEmp.addItem("Otra Empresa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNombreP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTApellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTApellido2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTelefono = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFDni = new javax.swing.JFormattedTextField();
        jBCancelar = new javax.swing.JButton();
        jCBEvento = new javax.swing.JComboBox();
        jCBNifEmp = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMMenu = new javax.swing.JMenu();
        jMIAltaPerson = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIListadoPerson = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta Asistentes");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        jLabel1.setText("Asistentes:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("1º Apellido:");

        jLabel4.setText("2º Apellido:");

        jLabel5.setText("Telefono:");

        try {
            jFTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Nif de Empresa:");

        jLabel7.setText("Dni:");

        try {
            jFDni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jCBEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione un Evento --" }));

        jCBNifEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Eliga Nif --" }));

        jMMenu.setText("Menu");

        jMIAltaPerson.setText("Alta");
        jMIAltaPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAltaPersonActionPerformed(evt);
            }
        });
        jMMenu.add(jMIAltaPerson);
        jMMenu.add(jSeparator1);

        jMIListadoPerson.setText("Listado");
        jMIListadoPerson.setEnabled(false);
        jMMenu.add(jMIListadoPerson);

        jMenuBar1.add(jMMenu);

        jMenu2.setText("Cancelar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jTApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jCBNifEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jFDni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCBEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCBNifEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBCancelar)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        ejercicioDBO4.VAltaASIS_Ant();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        jBCancelar.doClick();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMIAltaPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAltaPersonActionPerformed
        boolean dok = true;
        try{
            if(jFDni.getText().isEmpty()||jTNombreP.getText().isEmpty()||jTApellido1.getText().isEmpty()||jTApellido2.getText().isEmpty()
                    ||jFTelefono.getText().isEmpty()){throw new DatoVacio();}
            
            if(jCBEvento.getSelectedIndex()<=0||jCBNifEmp.getSelectedIndex()<=0){throw new DatoVacio();}
            
            if(jCBNifEmp.getSelectedIndex()==jCBNifEmp.getItemCount()-1){
                dok = false;
                ejercicioDBO4.Sig_VAltaEmp();
            }
            if(dok==true){
                //AsistenteAlta
                
                jCBEvento.removeAllItems();
                jCBEvento.addItem("-- Seleccione un Evento --");
                ArrayList<String> ListaCB = new ArrayList();
                //RllenarCBEvent
                
                for(int x = 0; ListaCB.size()>x; x++){
                    String Nombre = ListaCB.get(x);
                    jCBEvento.addItem(Nombre);
                }
                
                JOptionPane.showMessageDialog(this,"Asistente dado de alta.");
                jCBEvento.setSelectedIndex(0);
                jFDni.setText(null);
                jTNombreP.setText(null);
                jTApellido1.setText(null);
                jTApellido2.setText(null);
                jFTelefono.setText(null);
                jCBNifEmp.setSelectedIndex(0);
                
            }
            
        }catch(DatoVacio Ex){JOptionPane.showMessageDialog(this,"Error:\n Todo los datos son obligatorios"); dok=false;
        }catch(Exception Ex){JOptionPane.showMessageDialog(this,"Error:\n"+Ex.getMessage()); dok=false;}
    }//GEN-LAST:event_jMIAltaPersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAltaPerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox jCBEvento;
    private javax.swing.JComboBox jCBNifEmp;
    private javax.swing.JFormattedTextField jFDni;
    private javax.swing.JFormattedTextField jFTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMIAltaPerson;
    private javax.swing.JMenuItem jMIListadoPerson;
    private javax.swing.JMenu jMMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTApellido1;
    private javax.swing.JTextField jTApellido2;
    private javax.swing.JTextField jTNombreP;
    // End of variables declaration//GEN-END:variables
}
